"""Measure `ruleproof compile` on a corpus of public agent instruction files.

Downloads every file listed in sources.txt (pinned to a commit) into .cache/, compiles each one
on its own, and writes results.json plus a results.md table: directives, compiled directives and
coverage per file, and rule counts per recogniser. The downloaded files are not committed.

    uv run python bench/corpus/measure.py               # download as needed, measure
    uv run python bench/corpus/measure.py --offline     # cache only
    uv run python bench/corpus/measure.py --sample 40   # also print 40 rules to review by hand
"""

from __future__ import annotations

import argparse
import json
import random
import sys
import urllib.request
from collections import Counter
from pathlib import Path

from ruleproof.compile import CompileResult, compile_files, render_toml

HERE = Path(__file__).resolve().parent
CACHE = HERE / ".cache"
REVIEW_HEADING = "## Precision review"


def read_sources(path: Path) -> list[tuple[str, str, str]]:
    out = []
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if line and not line.startswith("#"):
            repo, rel, sha = line.split()
            out.append((repo, rel, sha))
    return out


def fetch(repo: str, rel: str, sha: str, offline: bool) -> Path | None:
    root = CACHE / repo.replace("/", "__") / sha
    target = root / rel
    if target.is_file():
        return target
    if offline:
        return None
    url = f"https://raw.githubusercontent.com/{repo}/{sha}/{rel}"
    try:
        with urllib.request.urlopen(url, timeout=30) as resp:
            data = resp.read()
    except OSError as exc:
        print(f"skip {repo}/{rel}: {exc}", file=sys.stderr)
        return None
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_bytes(data)
    return target


def measure(offline: bool) -> tuple[list[dict[str, object]], list[tuple[str, CompileResult]]]:
    rows: list[dict[str, object]] = []
    results: list[tuple[str, CompileResult]] = []
    for repo, rel, sha in read_sources(HERE / "sources.txt"):
        path = fetch(repo, rel, sha, offline)
        if path is None:
            continue
        root = CACHE / repo.replace("/", "__") / sha
        result = compile_files([path], root)
        name = f"{repo}/{rel}"
        results.append((name, result))
        compiled = len(result.directives) - len(result.uncovered)
        rows.append(
            {
                "file": name,
                "sha": sha,
                "directives": len(result.directives),
                "compiled": compiled,
                "rules": len(result.rules),
                "coverage": round(result.coverage, 3),
                "by_pattern": dict(Counter(cr.pattern for cr in result.rules)),
            }
        )
    return rows, results


def write_reports(rows: list[dict[str, object]], results: list[tuple[str, CompileResult]]) -> None:
    directives = sum(int(str(r["directives"])) for r in rows)
    compiled = sum(int(str(r["compiled"])) for r in rows)
    rules = [cr for _, res in results for cr in res.rules]
    by_pattern = Counter(cr.pattern for cr in rules)
    by_check = Counter(cr.rule.check for cr in rules)
    warnings = sum(1 for cr in rules if cr.rule.severity == "warning")
    totals = {
        "files": len(rows),
        "directives": directives,
        "compiled": compiled,
        "rules": len(rules),
        "warnings": warnings,
        "coverage": round(compiled / directives, 3) if directives else 0.0,
        "by_pattern": dict(sorted(by_pattern.items())),
        "by_check": dict(sorted(by_check.items())),
    }
    (HERE / "results.json").write_text(
        json.dumps({"totals": totals, "files": rows}, indent=2) + "\n", encoding="utf-8"
    )

    md = [
        "# `ruleproof compile` on public instruction files",
        "",
        "Generated by `measure.py` from the files pinned in `sources.txt`. Each file is compiled",
        "on its own with an empty repository (so layout-dependent globs fall back to defaults).",
        "",
        f"**{len(rows)} files, {directives} directives, {compiled} compiled "
        f"({totals['coverage']:.1%}), {len(rules)} rules ({warnings} warnings).**",
        "",
        "| Recogniser | Rules |",
        "| --- | ---: |",
        *(f"| `{p}` | {n} |" for p, n in sorted(by_pattern.items(), key=lambda x: -x[1])),
        "",
        "| File | Directives | Compiled | Rules | Coverage |",
        "| --- | ---: | ---: | ---: | ---: |",
        *(
            f"| {r['file']} | {r['directives']} | {r['compiled']} | {r['rules']} | "
            f"{float(str(r['coverage'])):.0%} |"
            for r in rows
        ),
        "",
    ]
    out = HERE / "results.md"
    review = ""
    if out.is_file():
        old = out.read_text(encoding="utf-8")
        if REVIEW_HEADING in old:
            review = old[old.index(REVIEW_HEADING) :]
    out.write_text("\n".join(md) + ("\n" + review if review else ""), encoding="utf-8")


def print_sample(results: list[tuple[str, CompileResult]], n: int, seed: int) -> None:
    pool = [(name, cr) for name, res in results for cr in res.rules]
    for i, (name, cr) in enumerate(random.Random(seed).sample(pool, min(n, len(pool))), 1):
        params = json.dumps(cr.rule.params)
        print(f"{i:>2}. [{cr.pattern}] {name}:{cr.directive.line} ({cr.rule.severity})")
        print(f"    prose: {cr.directive.text[:300]}")
        print(f"    rule:  {cr.rule.check} {params}")


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--offline", action="store_true", help="use cached files only")
    ap.add_argument("--sample", type=int, default=0, help="print N random rules to review")
    ap.add_argument("--seed", type=int, default=0)
    ap.add_argument("--toml", metavar="DIR", help="also write each file's rendered TOML here")
    args = ap.parse_args()

    rows, results = measure(args.offline)
    write_reports(rows, results)
    if args.toml:
        out = Path(args.toml)
        out.mkdir(parents=True, exist_ok=True)
        for name, res in results:
            (out / (name.replace("/", "__") + ".toml")).write_text(
                render_toml(res), encoding="utf-8"
            )
    if args.sample:
        print_sample(results, args.sample, args.seed)
    totals = json.loads((HERE / "results.json").read_text(encoding="utf-8"))["totals"]
    print(json.dumps(totals, indent=2), file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
